// ============================================================
// data.js — Static game data: biomes, seeds, constants
// ============================================================

export const BIOMES = {
  plains: {
    id: 'plains', name: 'Plains', icon: '🌾',
    desc: 'Open grassland. Good sunlight, moderate rainfall, shallow groundwater.',
    sunlight: 0.80,       // fraction of max possible (0-1)
    rainfall: 0.55,
    groundwaterDepth: 2,  // 1=shallow, 5=very deep
    soilNutrients: 0.55,
    soilType: 'loam',
    tempRange: [5, 30],   // °C seasonal range
    wind: 0.3,            // 0=calm, negative=leftward, positive=rightward (-1 to 1)
    seeds: ['grass', 'wildflower', 'shrub', 'oak', 'sunflower'],
  },
  forest: {
    id: 'forest', name: 'Forest', icon: '🌲',
    desc: 'Dense woodland. Filtered sunlight, high rainfall, rich soil.',
    sunlight: 0.50,
    rainfall: 0.80,
    groundwaterDepth: 2,
    soilNutrients: 0.80,
    soilType: 'clay-loam',
    tempRange: [0, 25],
    wind: 0.0,            // sheltered — calm
    seeds: ['oak', 'fern', 'moss', 'pine', 'shrub'],
  },
  desert: {
    id: 'desert', name: 'Desert', icon: '🏜️',
    desc: 'Arid wasteland. Intense sunlight, almost no rain, deep groundwater.',
    sunlight: 0.95,
    rainfall: 0.08,
    groundwaterDepth: 5,
    soilNutrients: 0.20,
    soilType: 'sand',
    tempRange: [10, 48],
    wind: 0.5,            // hot desert wind from one side
    seeds: ['cactus', 'shrub', 'succulent', 'drygrass'],
  },
  wetlands: {
    id: 'wetlands', name: 'Wetlands', icon: '🌿',
    desc: 'Marshy lowlands. Moderate sun, abundant water, waterlogged soil.',
    sunlight: 0.60,
    rainfall: 0.90,
    groundwaterDepth: 1,
    soilNutrients: 0.70,
    soilType: 'clay',
    tempRange: [8, 28],
    wind: -0.2,           // gentle breeze from right
    seeds: ['reed', 'fern', 'moss', 'willow', 'wildflower'],
  },
  mountain: {
    id: 'mountain', name: 'Mountain', icon: '⛰️',
    desc: 'High altitude slopes. Strong wind, cold temps, thin rocky soil.',
    sunlight: 0.70,
    rainfall: 0.60,
    groundwaterDepth: 4,
    soilNutrients: 0.30,
    soilType: 'rocky',
    tempRange: [-10, 20],
    wind: -0.8,           // strong prevailing wind from the right
    seeds: ['pine', 'shrub', 'moss', 'drygrass'],
  },
  tropical: {
    id: 'tropical', name: 'Tropical', icon: '🌴',
    desc: 'Lush rainforest. Bright light, constant rain, incredibly rich soil.',
    sunlight: 0.75,
    rainfall: 0.95,
    groundwaterDepth: 1,
    soilNutrients: 0.90,
    soilType: 'loam',
    tempRange: [22, 38],
    wind: 0.1,            // very light tropical breeze
    seeds: ['palm', 'fern', 'vine', 'oak', 'wildflower'],
  },
};

export const SEEDS = {
  oak: {
    id: 'oak', name: 'Oak Tree', icon: '🌰', rarity: 'uncommon',
    desc: 'Slow-growing but mighty. Excellent structural roots, dense canopy and long-lived.',
    growthRate: 0.6,
    startEnergy: 60, startWater: 50, startNutrients: 40,
    trunkStrength: 1.4,
    rootEfficiency: 1.0,
    leafEfficiency: 1.1,
    waterNeed: 1.0,
    energyNeed: 0.9,
    maxHeight: 120,
    maxSpread: 80,
  },
  pine: {
    id: 'pine', name: 'Pine Tree', icon: '🌲', rarity: 'common',
    desc: 'Needle leaves shed less water. Thrives in cold, poor soil. Tap-root focused.',
    growthRate: 0.7,
    startEnergy: 55, startWater: 45, startNutrients: 35,
    trunkStrength: 1.2,
    rootEfficiency: 1.2,
    leafEfficiency: 0.8,
    waterNeed: 0.7,
    energyNeed: 0.8,
    maxHeight: 100,
    maxSpread: 40,
  },
  cactus: {
    id: 'cactus', name: 'Cactus', icon: '🌵', rarity: 'uncommon',
    desc: 'Extreme water storage. Survives drought but grows slowly. Spines deter grazers.',
    growthRate: 0.35,
    startEnergy: 40, startWater: 80, startNutrients: 20,
    trunkStrength: 0.9,
    rootEfficiency: 0.9,
    leafEfficiency: 0.5,
    waterNeed: 0.2,
    energyNeed: 0.7,
    maxHeight: 40,
    maxSpread: 20,
  },
  fern: {
    id: 'fern', name: 'Fern', icon: '🌿', rarity: 'common',
    desc: 'Ancient low-growing plant. Loves shade and moisture. No seeds — spores only.',
    growthRate: 1.1,
    startEnergy: 35, startWater: 65, startNutrients: 50,
    trunkStrength: 0.4,
    rootEfficiency: 0.9,
    leafEfficiency: 1.4,
    waterNeed: 1.2,
    energyNeed: 0.6,
    maxHeight: 8,
    maxSpread: 15,
  },
  wildflower: {
    id: 'wildflower', name: 'Wildflower', icon: '🌸', rarity: 'common',
    desc: 'Fast-growing annual. Quick to flower and seed. Attracts pollinators.',
    growthRate: 1.5,
    startEnergy: 30, startWater: 35, startNutrients: 30,
    trunkStrength: 0.3,
    rootEfficiency: 0.7,
    leafEfficiency: 1.2,
    waterNeed: 0.8,
    energyNeed: 1.0,
    maxHeight: 5,
    maxSpread: 5,
  },
  sunflower: {
    id: 'sunflower', name: 'Sunflower', icon: '🌻', rarity: 'uncommon',
    desc: 'Tracks the sun for maximum energy. Needs good soil and water to grow tall.',
    growthRate: 1.2,
    startEnergy: 50, startWater: 50, startNutrients: 55,
    trunkStrength: 0.7,
    rootEfficiency: 0.8,
    leafEfficiency: 1.5,
    waterNeed: 1.1,
    energyNeed: 1.3,
    maxHeight: 12,
    maxSpread: 10,
  },
  shrub: {
    id: 'shrub', name: 'Shrub', icon: '🌱', rarity: 'common',
    desc: 'Resilient multi-stemmed plant. Balanced growth, good in most biomes.',
    growthRate: 0.9,
    startEnergy: 45, startWater: 45, startNutrients: 45,
    trunkStrength: 0.8,
    rootEfficiency: 1.0,
    leafEfficiency: 1.0,
    waterNeed: 0.9,
    energyNeed: 0.9,
    maxHeight: 20,
    maxSpread: 25,
  },
  grass: {
    id: 'grass', name: 'Grass', icon: '🌾', rarity: 'common',
    desc: 'Simplest form. Explosive lateral root spread. Very fast early growth.',
    growthRate: 2.0,
    startEnergy: 20, startWater: 30, startNutrients: 25,
    trunkStrength: 0.1,
    rootEfficiency: 1.3,
    leafEfficiency: 1.0,
    waterNeed: 0.6,
    energyNeed: 0.7,
    maxHeight: 2,
    maxSpread: 30,
  },
  moss: {
    id: 'moss', name: 'Moss', icon: '🍀', rarity: 'common',
    desc: 'No roots — absorbs water directly. Thrives in shade and humidity.',
    growthRate: 0.8,
    startEnergy: 25, startWater: 70, startNutrients: 30,
    trunkStrength: 0.05,
    rootEfficiency: 0.4,
    leafEfficiency: 1.3,
    waterNeed: 1.5,
    energyNeed: 0.4,
    maxHeight: 0.5,
    maxSpread: 20,
  },
  succulent: {
    id: 'succulent', name: 'Succulent', icon: '🪴', rarity: 'uncommon',
    desc: 'Thick water-storing leaves. Extremely drought-resistant. Slow but steady.',
    growthRate: 0.5,
    startEnergy: 45, startWater: 75, startNutrients: 25,
    trunkStrength: 0.6,
    rootEfficiency: 0.8,
    leafEfficiency: 0.9,
    waterNeed: 0.25,
    energyNeed: 0.8,
    maxHeight: 6,
    maxSpread: 8,
  },
  palm: {
    id: 'palm', name: 'Palm Tree', icon: '🌴', rarity: 'rare',
    desc: 'Tall single-trunk tropical giant. Loves heat and light. Deep tap-root.',
    growthRate: 0.8,
    startEnergy: 65, startWater: 60, startNutrients: 50,
    trunkStrength: 1.1,
    rootEfficiency: 1.1,
    leafEfficiency: 1.2,
    waterNeed: 1.0,
    energyNeed: 1.1,
    maxHeight: 60,
    maxSpread: 20,
  },
  willow: {
    id: 'willow', name: 'Willow', icon: '🎋', rarity: 'rare',
    desc: 'Weeping tree of waterways. Extraordinary water uptake. Flexible branches.',
    growthRate: 1.0,
    startEnergy: 55, startWater: 70, startNutrients: 60,
    trunkStrength: 1.0,
    rootEfficiency: 1.5,
    leafEfficiency: 1.1,
    waterNeed: 1.8,
    energyNeed: 0.9,
    maxHeight: 50,
    maxSpread: 60,
  },
  drygrass: {
    id: 'drygrass', name: 'Dry Grass', icon: '🌵', rarity: 'common',
    desc: 'Hardy desert grass. Near-zero water use. Dormant in drought.',
    growthRate: 0.9,
    startEnergy: 15, startWater: 20, startNutrients: 15,
    trunkStrength: 0.1,
    rootEfficiency: 1.1,
    leafEfficiency: 0.7,
    waterNeed: 0.3,
    energyNeed: 0.6,
    maxHeight: 1.5,
    maxSpread: 15,
  },
  reed: {
    id: 'reed', name: 'Reed', icon: '🌾', rarity: 'common',
    desc: 'Wetland specialist. Thrives in waterlogged soil. Rapid vertical growth.',
    growthRate: 1.3,
    startEnergy: 40, startWater: 80, startNutrients: 45,
    trunkStrength: 0.5,
    rootEfficiency: 0.9,
    leafEfficiency: 1.1,
    waterNeed: 1.6,
    energyNeed: 0.8,
    maxHeight: 5,
    maxSpread: 12,
  },
  vine: {
    id: 'vine', name: 'Vine', icon: '🌿', rarity: 'rare',
    desc: 'Climbing plant. Needs support to grow tall. Extraordinary leaf coverage.',
    growthRate: 1.4,
    startEnergy: 40, startWater: 55, startNutrients: 55,
    trunkStrength: 0.3,
    rootEfficiency: 0.9,
    leafEfficiency: 1.8,
    waterNeed: 1.1,
    energyNeed: 1.0,
    maxHeight: 30,
    maxSpread: 25,
  },
};

// Resource constants
export const RESOURCE_MAX = 100;
export const TICK_MS_BASE = 1000; // 1 real second = 1 game tick at speed ×1

export const ROOT_TYPES = {
  taproot: {
    id: 'taproot', name: 'Tap Root',
    desc: 'Drills deep to reach groundwater. Best for drought resistance.',
    icon: '⬇️',
    waterBonus: 1.8, nutrientBonus: 0.6, structuralBonus: 0.5,
  },
  structural: {
    id: 'structural', name: 'Structural Root',
    desc: 'Anchors the plant. Allows bigger trunk and branches.',
    icon: '↔️',
    waterBonus: 0.5, nutrientBonus: 0.7, structuralBonus: 2.0,
  },
  surface: {
    id: 'surface', name: 'Surface Root',
    desc: 'Spreads wide to catch rainwater and gather nutrients.',
    icon: '🌐',
    waterBonus: 1.2, nutrientBonus: 1.4, structuralBonus: 0.8,
  },
};
